### ISSUE TITLE
Bug when setting location

### ISSUE THREAD

**Issue by dougg0k** [mahor1221/reddish-shift#1]
Hi,

There is a bug when trying to set the location. If I start the value with a negative value, it will complain and not work. 

Positive values do work though.

```
reddish-shift daemon --location -123:-123
error: unexpected argument '-1' found

Usage: reddish-shift daemon [OPTIONS]

For more information, try '--help'.
```

---

I have a question, if I create the config file in one of the locations mentioned, do they get loaded automatically, if I run, the daemon or oneshot?

**Comment by mahor1221** [comment]
Thanks for the bug report, should be fixed now. 
Please try using `v0.1.2`.

---

> I have a question, if I create the config file in one of the locations mentioned, do they get loaded automatically, if I run, the daemon or oneshot?

Yes, the config file is loaded automatically for all commands except `print` (which doesn't require a config file).
For example, if you have set the adjustment method in the config file, it will be used by `set`, `reset`, `oneshot` and `daemon`.

Also, CLI arguments have a higher priority than values provided by the config file. This means that if you enter `method = "vidmode"` in the config file, but also provide the `--method randr` argument, the adjustment method would be `randr`.

**Comment by dougg0k** [comment]
Cool. Thanks.
